DROP DATABASE IF EXISTS bd;

CREATE DATABASE bd;



USE bd;



CREATE TABLE JUGADOR (

	ID INT NOT NULL,

	NOMBRE VARCHAR (99),

	PRIMARY KEY (ID)

)Engine=InnoDB;



CREATE TABLE PUNTOSPOSIBLES (

	ID INT NOT NULL,

	NOMBRE VARCHAR (99),

	PUNTOS1 INT,

	PRIMARY KEY (ID)

)Engine=InnoDB;



CREATE TABLE PUNTOSTOTALES (

	ID_J INT,

	ID_P INT,

	SUMATOTAL INT,

	FOREIGN KEY (ID_J) REFERENCES JUGADOR(ID),

	FOREIGN KEY (ID_P) REFERENCES PUNTOSPOSIBLES(ID)



)ENGINE=InnoDB;



INSERT INTO JUGADOR VALUES (1, 'Guille');

INSERT INTO JUGADOR VALUES (2, 'PAU');

INSERT INTO JUGADOR VALUES (3, 'ADE');

INSERT INTO JUGADOR VALUES (4, 'DANI');



INSERT INTO PUNTOSPOSIBLES VALUES (1, '1PUNTO', 1);

INSERT INTO PUNTOSPOSIBLES VALUES (2, '2PUNTOS', 2);

INSERT INTO PUNTOSPOSIBLES VALUES (3, '3PUNTOS', 3);

INSERT INTO PUNTOSPOSIBLES VALUES (4, '4PUNTOS', 4);

INSERT INTO PUNTOSPOSIBLES VALUES (5, '5PUNTOS', 5);

INSERT INTO PUNTOSPOSIBLES VALUES (6, '6PUNTOS', 6);

INSERT INTO PUNTOSPOSIBLES VALUES (7, '7PUNTOS', 7);

INSERT INTO PUNTOSPOSIBLES VALUES (8, '8PUNTOS', 8);

INSERT INTO PUNTOSPOSIBLES VALUES (9, '9PUNTOS', 9);

INSERT INTO PUNTOSPOSIBLES VALUES (10, '10PUNTOS', 10);

INSERT INTO PUNTOSPOSIBLES VALUES (11, '11PUNTOS', 11);

INSERT INTO PUNTOSPOSIBLES VALUES (12, '12PUNTOS', 12);

INSERT INTO PUNTOSPOSIBLES VALUES (13, '13PUNTOS', 13);

INSERT INTO PUNTOSPOSIBLES VALUES (14, '14PUNTOS', 14);

INSERT INTO PUNTOSPOSIBLES VALUES (15, '15PUNTOS', 15);



INSERT INTO PUNTOSTOTALES VALUES (1, 10, 3);

INSERT INTO PUNTOSTOTALES VALUES (2, 9, 3);

INSERT INTO PUNTOSTOTALES VALUES (3, 11, 3);

INSERT INTO PUNTOSTOTALES VALUES (4, 7, 3);





/* dime si alguien ha sumado 10 puntos */



SELECT JUGADOR.NOMBRE FROM (JUGADOR, PUNTOSPOSIBLES, PUNTOSTOTALES)

WHERE PUNTOSPOSIBLES.NOMBRE = '10PUNTOS'

AND PUNTOSPOSIBLES.ID = PUNTOSTOTALES.ID_P

AND PUNTOSTOTALES.ID_J = JUGADOR.ID;











	

